"""Initial Migration

Revision ID: caa21d402226
Revises: 
Create Date: 2024-07-26 12:57:46.317663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caa21d402226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Leads')
    op.drop_table('Contacts')
    op.drop_table('Users')
    op.drop_table('Activities')
    op.drop_table('OrderDetails')
    op.drop_table('Clients')
    op.drop_table('SupportTickets')
    op.drop_table('Sales')
    op.drop_table('Oppurtunities')
    op.drop_table('Orders')
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AccountID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('CompanyName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('CompanyRevenue',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('EmployeeHeadCount',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('Country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.alter_column('Country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('EmployeeHeadCount',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('CompanyRevenue',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('CompanyName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('AccountID')

    op.create_table('Orders',
    sa.Column('OrderID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AccountID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OrderDate', sa.DATE(), nullable=True),
    sa.Column('TotalAmount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Status', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Oppurtunities',
    sa.Column('OpportunityID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AccountID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OppurtunityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Value_', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Stage', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CloseDate', sa.DATE(), nullable=True),
    sa.Column('CreationDate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('OpportunityID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Sales',
    sa.Column('SaleID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('OppurtunityID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SaleAmount', mysql.FLOAT(), nullable=True),
    sa.Column('SaleDate', sa.DATE(), nullable=True),
    sa.Column('SalesRep', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Commission', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('SaleID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('SupportTickets',
    sa.Column('TicketID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AccountID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ContactID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Issue', mysql.TEXT(), nullable=True),
    sa.Column('Status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Priority', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('DateCreated', sa.DATE(), nullable=True),
    sa.Column('DateResolved', sa.DATE(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Clients',
    sa.Column('ClientID', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Subscriber', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Image', sa.BLOB(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('OrderDetails',
    sa.Column('OrderDetailID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OrderID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Discount', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Activities',
    sa.Column('ActivityID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AccountID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ContactID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ActivityType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Subject_', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Description_', mysql.TEXT(), nullable=True),
    sa.Column('ActivityDate', sa.DATE(), nullable=True),
    sa.Column('Status_', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ActivityID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Users',
    sa.Column('UserID', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Password', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ClientID', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Subscriber', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ValidFrom', sa.DATE(), nullable=True),
    sa.Column('ValidTo', sa.DATE(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Contacts',
    sa.Column('ContactID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AccountID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FirstName', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Phone', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Role_', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('DateCreated', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('ContactID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Leads',
    sa.Column('Position', mysql.TEXT(), nullable=True),
    sa.Column('First Name', mysql.TEXT(), nullable=True),
    sa.Column('Last Name', mysql.TEXT(), nullable=True),
    sa.Column('Email', mysql.TEXT(), nullable=True),
    sa.Column('CompanyName', mysql.TEXT(), nullable=True),
    sa.Column('LeadID', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
